### Default datasets

In [1]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

### 1. Load the datasets contained in the Seaborn library

#### We can get the names of the datasets in the library by the following method

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

### Load as a dataframe

In [3]:
df=sns.load_dataset('iris')
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

### Task

#### Load all the datasets and do the EDA

### 2. Scikit-learn datasets

In [4]:
from sklearn.datasets import fetch_california_housing

#### Load data (will download the data if it's the first time loading)

In [5]:
housing= fetch_california_housing(as_frame=True)

### Create a dataframe

In [6]:
df=housing['data'].join(housing['target'])
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

#### Task: Load other datasets and do the EDA

## 3. PYDATASET
##### You may need to pip install the pydataset library

In [10]:
from pydataset import data

initiated datasets repo at: C:\Users\USER\.pydataset/

#### Checkout the datasets

In [11]:
data()

        dataset_id                                             title
0    AirPassengers       Monthly Airline Passenger Numbers 1949-1960
1          BJsales                 Sales Data with Leading Indicator
2              BOD                         Biochemical Oxygen Demand
3     Formaldehyde                     Determination of Formaldehyde
4     HairEyeColor         Hair and Eye Color of Statistics Students
..             ...                                               ...
752        VerbAgg                  Verbal Aggression item responses
753           cake                 Breakage Angle of Chocolate Cakes
754           cbpp                 Contagious bovine pleuropneumonia
755    grouseticks  Data on red grouse ticks from Elston et al. 2001
756     sleepstudy       Reaction times in a sleep deprivation study

[757 rows x 2 columns]

#### FIND 20th DATAset info

In [13]:
data().iloc[20]

dataset_id                                               USJudgeRatings
title         Lawyers' Ratings of State Judges in the US Superior Court
Name: 20, dtype: object

In [15]:
df1=data('USJudgeRatings')
df1

,CONT,INTG,DMNR,DILG,CFMG,DECI,PREP,FAMI,ORAL,WRIT,PHYS,RTEN
"AARONSON,L.H.",5.7,7.9,7.7,7.3,7.1,7.4,7.1,7.1,7.1,7.0,8.3,7.8
"ALEXANDER,J.M.",6.8,8.9,8.8,8.5,7.8,8.1,8.0,8.0,7.8,7.9,8.5,8.7
"ARMENTANO,A.J.",7.2,8.1,7.8,7.8,7.5,7.6,7.5,7.5,7.3,7.4,7.9,7.8
"BERDON,R.I.",6.8,8.8,8.5,8.8,8.3,8.5,8.7,8.7,8.4,8.5,8.8,8.7
"BRACKEN,J.J.",7.3,6.4,4.3,6.5,6.0,6.2,5.7,5.7,5.1,5.3,5.5,4.8
"BURNS,E.B.",6.2,8.8,8.7,8.5,7.9,8.0,8.1,8.0,8.0,8.0,8.6,8.6
"CALLAHAN,R.J.",10.6,9.0,8.9,8.7,8.5,8.5,8.5,8.5,8.6,8.4,9.1,9.0
"COHEN,S.S.",7.0,5.9,4.9,5.1,5.4,5.9,4.8,5.1,4.7,4.9,6.8,5.0
"DALY,J.J.",7.3,8.9,8.9,8.7,8.6,8.5,8.4,8.4,8.4,8.5,8.8,8.8
"DANNEHY,J.F.",8.2,7.9,6.7,8.1,7.9,8.0,7.9,8.1,7.7,7.8,8.5,7.9
"DEAN,H.H.",7.0,8.0,7.6,7.4,7.3,7.5,7.1,7.2,7.1,7.2,8.4,7.7
"DEVITA,H.J.",6.5,8.0,7.6,7.2,7.0,7.1,6.9,7.0,7.0,7.1,6.9,7.2
"DRISCOLL,P.J.",6.7,8.6,8.2,6.8,6.9,6.6,7.1,7.3,7.2,7.2,8.1,7.7
"GRILLO,A.E.",7.0,7.5,6.4,6.8,6.5,7.0,6.6,6.8,6.3,6.6,6.2,6.5
"HADDEN,W.L.JR.",6.5,8.1,8.0,8.0,7.9,8.0,7.9,7.8,7.8,7.8,8.4,8.0
"HAMILL,E.C.",7.3,8.0,7.4,7.7,7.3,7.3,7.3,7.2,7.1,7.2,8.0,7.6
HEALEY.A.H.,8.0,7.6,6.6,7.2,6.5,6.5,6.8,6.7,6.4,6.5,6.9,6.7
"HULL,T.C.",7.7,7.7,6.7,7.5,7.4,7.5,7.1,7.3,7.1,7.3,8.1,7.4
"LEVINE,I.",8.3,8.2,7.4,7.8,7.7,7.7,7.7,7.8,7.5,7.6,8.0,8.0
"LEVISTER,R.L.",9.6,6.9,5.7,6.6,6.9,6.6,6.2,6.0,5.8,5.8,7.2,6.0
"MARTIN,L.F.",7.1,8.2,7.7,7.1,6.6,6.6,6.7,6.7,6.8,6.8,7.5,7.3
"MCGRATH,J.F.",7.6,7.3,6.9,6.8,6.7,6.8,6.4,6.3,6.3,6.3,7.4,6.6
"MIGNONE,A.F.",6.6,7.4,6.2,6.2,5.4,5.7,5.8,5.9,5.2,5.8,4.7,5.2
"MISSAL,H.M.",6.2,8.3,8.1,7.7,7.4,7.3,7.3,7.3,7.2,7.3,7.8,7.6
"MULVEY,H.M.",7.5,8.7,8.5,8.6,8.5,8.4,8.5,8.5,8.4,8.4,8.7,8.7
"NARUK,H.J.",7.8,8.9,8.7,8.9,8.7,8.8,8.9,9.0,8.8,8.9,9.0,9.0
"O'BRIEN,F.J.",7.1,8.5,8.3,8.0,7.9,7.9,7.8,7.8,7.8,7.7,8.3,8.2
"O'SULLIVAN,T.J.",7.5,9.0,8.9,8.7,8.4,8.5,8.4,8.3,8.3,8.3,8.8,8.7
"PASKEY,L.",7.5,8.1,7.7,8.2,8.0,8.1,8.2,8.4,8.0,8.1,8.4,8.1
"RUBINOW,J.E.",7.1,9.2,9.0,9.0,8.4,8.6,9.1,9.1,8.9,9.0,8.9,9.2
SADEN.G.A.,6.6,7.4,6.9,8.4,8.0,7.9,8.2,8.4,7.7,7.9,8.4,7.5
"SATANIELLO,A.G.",8.4,8.0,7.9,7.9,7.8,7.8,7.6,7.4,7.4,7.4,8.1,7.9
"SHEA,D.M.",6.9,8.5,7.8,8.5,8.1,8.2,8.4,8.5,8.1,8.3,8.7,8.3
"SHEA,J.F.JR.",7.3,8.9,8.8,8.7,8.4,8.5,8.5,8.5,8.4,8.4,8.8,8.8
"SIDOR,W.J.",7.7,6.2,5.1,5.6,5.6,5.9,5.6,5.6,5.3,5.5,6.3,5.3
"SPEZIALE,J.A.",8.5,8.3,8.1,8.3,8.4,8.2,8.2,8.1,7.9,8.0,8.0,8.2
"SPONZO,M.J.",6.9,8.3,8.0,8.1,7.9,7.9,7.9,7.7,7.6,7.7,8.1,8.0
"STAPLETON,J.F.",6.5,8.2,7.7,7.8,7.6,7.7,7.7,7.7,7.5,7.6,8.5,7.7
"TESTO,R.J.",8.3,7.3,7.0,6.8,7.0,7.1,6.7,6.7,6.7,6.7,8.0,7.0
"TIERNEY,W.L.JR.",8.3,8.2,7.8,8.3,8.4,8.3,7.7,7.6,7.5,7.7,8.1,7.9
"WALL,R.A.",9.0,7.0,5.9,7.0,7.0,7.2,6.9,6.9,6.5,6.6,7.6,6.6
"WRIGHT,D.B.",7.1,8.4,8.4,7.7,7.5,7.7,7.8,8.2,8.0,8.1,8.3,8.1
"ZARRILLI,K.J.",8.6,7.4,7.0,7.5,7.5,7.7,7.4,7.2,6.9,7.0,7.8,7.1

In [16]:
df1.isnull().mean()*100

CONT    0.0
INTG    0.0
DMNR    0.0
DILG    0.0
CFMG    0.0
DECI    0.0
PREP    0.0
FAMI    0.0
ORAL    0.0
WRIT    0.0
PHYS    0.0
RTEN    0.0
dtype: float64

#### Loading the BOD Dataset

In [17]:
df= data('BOD')
df

   Time  demand
1     1     8.3
2     2    10.3
3     3    19.0
4     4    16.0
5     5    15.6
6     7    19.8